name: Build Docs Page
on:
  push:
    branches:
      - docs
      
permissions:
  contents: write

jobs:
  build-and-deploy:
    concurrency: ci-${{ github.ref }} # Recommended if you intend to make multiple deployments in quick succession.
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3
        
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
         python-version: 3.8

      - name: Install and Build 🔧
        run: |
         python -m pip install --upgrade pip
         pip install mkdocs-material
         mkdocs build
      - name: Deploy documentation
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GOOGLE_ANALYTICS_KEY: ${{ secrets.GOOGLE_ANALYTICS_KEY }}
        run: |
          mkdocs gh-deploy --force
